wget -c http://www.openbioinformatics.org/annovar/download/hg19_refGene.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_refGeneMrna.fa.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_refGeneVersion.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_refGene.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_refGeneMrna.fa.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_refGeneVersion.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_refGeneWithVer.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_refGeneWithVerMrna.fa.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_refGeneWithVer.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_refGeneWithVerMrna.fa.gz
wget -c http://hgdownload.cse.ucsc.edu/goldenPath/hs1/database/refGene.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_knownGene.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_kgXref.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_knownGeneMrna.fa.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_knownGene.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_kgXref.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_knownGeneMrna.fa.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_ensGene.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_ensGeneMrna.fa.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_ensGene.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_ensGeneMrna.fa.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_ensGene.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_ensGeneMrna.fa.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_ensGene.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_ensGeneMrna.fa.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_1000g2015aug.zip
wget -c http://www.openbioinformatics.org/annovar/download/hg38_1000g2015aug.zip
wget -c http://www.openbioinformatics.org/annovar/download/hg19_avsnp151.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_avsnp151.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_avsnp151.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_avsnp151.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_nci60.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_nci60.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_nci60.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_nci60.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_clinvar_20240611.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_clinvar_20240611.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_clinvar_20240611.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_clinvar_20240611.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_gnomad211_genome.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_gnomad211_genome.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_gnomad41_genome.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_gnomad41_genome.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hs1_gnomad_genome.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hs1_gnomad_genome.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_gnomad211_exome.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_gnomad211_exome.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_gnomad41_exome.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_gnomad41_exome.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_exac03.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_exac03.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_exac03.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_exac03.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_esp6500siv2_all.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_esp6500siv2_all.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_esp6500siv2_all.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_esp6500siv2_all.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_intervar_20180118.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_intervar_20180118.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_intervar_20180118.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_intervar_20180118.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_dbnsfp47a_interpro.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg19_dbnsfp47a_interpro.txt.idx.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_dbnsfp47a_interpro.txt.gz
wget -c http://www.openbioinformatics.org/annovar/download/hg38_dbnsfp47a_interpro.txt.idx.gz
wget -c http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/gwasCatalog.txt.gz
wget -c http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/gwasCatalog.txt.gz